# 第1章 機械学習の準備

## 1.1. 機械学習について

## 1.3. Jupyter Notebook

In [1]:
1/3

0.3333333333333333

In [3]:
1+2+3

6

## 1.4. KerasとTensorFlowのインストール

In [6]:
import keras

In [7]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [8]:
keras.__version__

'2.4.2'

# 第2章 Pythonの基本

## 2.1. 四則演算

### 2.1.1. 四則演算の利用

In [9]:
1 + 2

3

In [10]:
(1 + 2 * 3 - 4) / 5

0.6

### 2.1.2. 累乗

In [11]:
2**8

256

## 2.2. 変数

### 2.2.1. 変数を利用した計算

In [13]:
x = 1
y = 1 / 3
x + y

1.3333333333333333

### 2.2.2. 変数名の表記

In [14]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

### 2.3.1.型の種類

In [15]:
a = 1

In [16]:
a = 1.5

In [19]:
a="learning"

In [20]:
b='abc'

In [21]:
True

True

In [22]:
False

False

In [23]:
a = [1,2,3]

In [24]:
a = (1,2,3)

In [25]:
b = (2)

### 2.3.2. 型の調査

In [27]:
type(100)

int

In [28]:
type(100.1)

float

In [29]:
x = 100

In [30]:
type(x)

int

In [31]:
x = 100.1
type(x)

float

### 2.3.3. 文字列

In [32]:
x = 'learning'
type(x)

str

## 2.4. print文

### 2.4.1. print文の応用

In [33]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

In [34]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


### 2.4.2. 文字列と組み合わせた数字の表示1

In [35]:
print('x= ' + str(x))

x= 0.3333333333333333


### 2.4.3. 文字列と組み合わせた数字の表示2

In [36]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


In [37]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print('weight = {0}kg, {1}kg, {2}kg'.format(x,y,z))

weight = 0.3333333333333333kg, 0.14285714285714285kg, 0.25kg


In [38]:
print('weight = {0:.2f}kg, {1:.2f}kg, {2:.2f}kg'.format(x,y,z))

weight = 0.33kg, 0.14kg, 0.25kg


## 2.5. list（リスト, 配列変数）

In [3]:
x = [1, 1, 2, 3, 5] # listの定義
print(x)

[1, 1, 2, 3, 5]


In [4]:
x[0]

1

In [5]:
x[1]

1

In [7]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


In [8]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


### 2.5.2. 2次元の配列

In [10]:
a = [[1, 2, 3],[4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [11]:
print(a[0][1])

2


In [12]:
x=[1, 1, 2, 3, 5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


### 2.5.3. listの長さ

In [13]:
x = [1, 1, 2, 3, 5]
len(x)

5

### 2.5.4. 連続した整数のデータの作成

In [15]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


In [16]:
print(y)

range(5, 10)


In [17]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 2.6. tuple(タプル)

### 2.6.1.tupleの利用

In [19]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


### 2.6.2. 要素の参照

In [20]:
a[1]

2

In [21]:
type(a)

tuple

### 2.6.3. 長さが1のtuple

In [22]:
a = (1)
type(a)

int

In [23]:
a = (1,)
type(a)

tuple

## 2.7. if文

### 2.7.1. if文の利用

In [24]:
x = 11
if x > 10:
    print('x is ')
    print('      larger than 10.')
else:
    print('x is smaller than 11.')

x is 
      larger than 10.


In [25]:
x > 10

True

In [26]:
type(x > 10)

bool

### 2.7.2 比較演算子

In [27]:
x = 10
if 10 <= x and x <= 20:
    print('x is between 10 and 20.')


x is between 10 and 20.


## 2.8 for文

### 2.8.1 for文の利用

In [28]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [30]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


### 2.8.2 enumerateの利用

In [31]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n*2
print(num)

[4, 8, 12, 16, 20]


## 2.9 ベクトル

In [32]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

### 2.9.1 numpyの利用

In [33]:
import numpy as np

### 2.9.2 ベクトルの定義

In [35]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [36]:
print(x)

[1 2 3]


In [37]:
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [38]:
type(x)

numpy.ndarray

### 2.9.3 要素の参照

In [39]:
x[0]

1

### 2.9.4 要素の書き換え

In [40]:
x[0] = 100
print(x)

[100   2   3]


### 2.9.5 連続した整数のベクトルの作成

In [42]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [43]:
print(np.arange(5, 10))

[5 6 7 8 9]


### 2.9.6 ndarray型の注意点

In [45]:
a = np.array([1, 1])
b = a
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [100   1]
b = [100   1]


In [46]:
a = np.array([1, 1])
b = a.copy()
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [1 1]
b = [100   1]


## 2.10 行列

### 2.10.1 行列の定義

In [48]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


### 2.10.2 行列のサイズ

In [50]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [51]:
w, h = x.shape
print(w)
print(h)

2
3


### 2.10.3 要素の参照

In [52]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]

6

### 2.10.4 要素の書き換え

In [53]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


### 2.10.5 要素が0や1のndarrayの作成

In [54]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [57]:
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
print(np.ones((2, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 2.10.6 要素がランダムな行列の生成

In [60]:
np.random.rand(2, 3)

array([[0.53370225, 0.09926697, 0.11149617],
       [0.94831332, 0.19738472, 0.02576397]])

### 2.10.7 行列のサイズの変更

In [61]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 2.11 行列(ndarray)の四則演算

## 2.11.1 行列における四則演算

In [63]:
x = np.array([[4,4,4], [8,8,8]])
y = np.array([[1,1,1], [2,2,2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


## 2.11.2 スカラー×行列

In [64]:
x = np.array([[4,4,4], [8,8,8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


## 2.11.3 算術関数

In [66]:
x = np.array([[4,4,4], [8,8,8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [68]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]
